// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqEltuZq-WkZb63Gcd-C0b8NXXlErTT8',
    appId: '1:391830778529:web:02b1e6883b63592340b6e0',
    messagingSenderId: '391830778529',
    projectId: 'swiftnex-f0a83',
    authDomain: 'swiftnex-f0a83.firebaseapp.com',
    storageBucket: 'swiftnex-f0a83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRd81U6pUIa8bozgPHzFTOCyl1nzG3Mo',
    appId: '1:391830778529:android:ad878198eb5ad26440b6e0',
    messagingSenderId: '391830778529',
    projectId: 'swiftnex-f0a83',
    storageBucket: 'swiftnex-f0a83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPcnhaOQpM2_bpt640qxOMet8oX4CzFnE',
    appId: '1:391830778529:ios:425a0465bb1410da40b6e0',
    messagingSenderId: '391830778529',
    projectId: 'swiftnex-f0a83',
    storageBucket: 'swiftnex-f0a83.firebasestorage.app',
    iosBundleId: 'com.example.swiftnex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPcnhaOQpM2_bpt640qxOMet8oX4CzFnE',
    appId: '1:391830778529:ios:425a0465bb1410da40b6e0',
    messagingSenderId: '391830778529',
    projectId: 'swiftnex-f0a83',
    storageBucket: 'swiftnex-f0a83.firebasestorage.app',
    iosBundleId: 'com.example.swiftnex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXqEltuZq-WkZb63Gcd-C0b8NXXlErTT8',
    appId: '1:391830778529:web:a839e9854c4effc840b6e0',
    messagingSenderId: '391830778529',
    projectId: 'swiftnex-f0a83',
    authDomain: 'swiftnex-f0a83.firebaseapp.com',
    storageBucket: 'swiftnex-f0a83.firebasestorage.app',
  );
}
